USE [master]
GO

/****** Object:  Database [blackjack]    Script Date: 24-Aug-18 11:51:46 ******/
CREATE DATABASE [blackjack]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'blackjack', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\blackjack.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'blackjack_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\blackjack_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [blackjack] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [blackjack].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [blackjack] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [blackjack] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [blackjack] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [blackjack] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [blackjack] SET ARITHABORT OFF 
GO

ALTER DATABASE [blackjack] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [blackjack] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [blackjack] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [blackjack] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [blackjack] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [blackjack] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [blackjack] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [blackjack] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [blackjack] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [blackjack] SET  ENABLE_BROKER 
GO

ALTER DATABASE [blackjack] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [blackjack] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [blackjack] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [blackjack] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [blackjack] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [blackjack] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [blackjack] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [blackjack] SET RECOVERY FULL 
GO

ALTER DATABASE [blackjack] SET  MULTI_USER 
GO

ALTER DATABASE [blackjack] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [blackjack] SET DB_CHAINING OFF 
GO

ALTER DATABASE [blackjack] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [blackjack] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [blackjack] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [blackjack] SET QUERY_STORE = OFF
GO

USE [blackjack]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [blackjack] SET  READ_WRITE 
GO

